### ISSUE TITLE
which version is pbr or how to fix it？

### ISSUE THREAD

**Issue by prehonor** [blambright/qstylizer#15]
ERROR: Command errored out with exit status 1:
     command: /nix/store/wl02plhc6zf84m6x9984l42wnnnbly5m-python3-3.9.6/bin/python3.9 -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/home/prehonor/Downloads/qstylizer-0.2.1/setup.py'"'"'; __file__='"'"'/home/prehonor/Downloads/qstylizer-0.2.1/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /run/user/1000/pip-pip-egg-info-n5ge8t1o
         cwd: /home/prehonor/Downloads/qstylizer-0.2.1/
    Complete output (16 lines):
    ERROR:root:Error parsing
    Traceback (most recent call last):
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/core.py", line 96, in pbr
        attrs = util.cfg_to_args(path, dist.script_args)
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/util.py", line 272, in cfg_to_args
        pbr.hooks.setup_hook(config)
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/hooks/__init__.py", line 25, in setup_hook
        metadata_config.run()
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/hooks/base.py", line 27, in run
        self.hook()
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/hooks/metadata.py", line 25, in hook
        self.config['version'] = packaging.get_version(
      File "/nix/store/vrwl3c3d3rpj0nhphjsm4m71wwsyc9gg-python3.9-pbr-5.7.0/lib/python3.9/site-packages/pbr/packaging.py", line 874, in get_version
        raise Exception("Versioning for this project requires either an sdist"
    Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name qstylizer was given, but was not able to be found.
    error in setup command: Error parsing /home/prehonor/Downloads/qstylizer-0.2.1/setup.cfg: Exception: Versioning for this project requires either an sdist tarball, or access to an upstream git repository. It's also possible that there is a mismatch between the package name in setup.cfg and the argument given to pbr.version.VersionInfo. Project name qstylizer was given, but was not able to be found.
    ----------------------------------------
WARNING: Discarding file:///home/prehonor/Downloads/qstylizer-0.2.1. Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

**Comment by blambright** [comment]
pbr needs a git tag to install from source. try installing from a cloned repo instead

**Comment by prehonor** [comment]
> pbr needs a git tag to install from source. try installing from a cloned repo instead

Thank you
