### ISSUE TITLE
Missing widgets and attributes

### ISSUE THREAD

**Issue by buddly27** [blambright/qstylizer#8]
Some widgets are missing when using the attribute form to create a stylesheet:

```python
>>> import qstylizer.style
>>> css = qstylizer.style.StyleSheet()
>>> css["QTextBrowser"]
<ClassRule name='QTextBrowser' />

>>> css.QTextBrowser
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'StyleSheet' object has no attribute 'QTextBrowser'
```

The following ones are missing:
* QTextBrowser
* QPlainTextEdit
* QScrollArea

The following CSS attributes are also missing:
* combobox-popup
* show-decoration-selected

```python
>>> css.QListView["show-decoration-selected"]
<StyleRule name='show-decoration-selected' />
>>> css.QListView.showDecorationSelected
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ClassRule' object has no attribute 'showDecorationSelected'
>>> 
>>> css.QComboBox["combobox-popup"]
<StyleRule name='combobox-popup' />
>>> css.QComboBox.comboboxPopup
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'ClassRule' object has no attribute 'comboboxPopup'

```

**Comment by blambright** [comment]
Released with qstylizer 0.1.10
